apiVersion: v1
kind: ConfigMap
metadata:
  name: projects-config
  namespace: projects-kiii
data:
  POSTGRES_DB: "kiii"
  POSTGRES_HOST: "database"
  POSTGRES_URL: "postgres-service.projects-kiii.svc.cluster.local"
---
apiVersion: v1
kind: Secret
metadata:
  name: projects-secret
  namespace: projects-kiii
type: Opaque
data:
  POSTGRES_USER: cG9zdGdyZXM=
  POSTGRES_PASSWORD: YWRtaW4=
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: projects
  namespace: projects-kiii
spec:
  replicas: 3
  selector:
    matchLabels:
      app: projects
  template:
    metadata:
      labels:
        app: projects
    spec:
      containers:
        - name: projects
          image: stefanvasilev2002/projects-kiii-image:latest
          ports:
            - containerPort: 8000
          env:
            - name: POSTGRES_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: projects-config
                  key: POSTGRES_DB
            - name: POSTGRES_USERNAME
              valueFrom:
                secretKeyRef:
                  name: projects-secret
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: projects-secret
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_URL
              valueFrom:
                configMapKeyRef:
                  name: projects-config
                  key: POSTGRES_URL
            - name: DATABASE_URL
              value: "postgres://$(POSTGRES_USER):$(POSTGRES_PASSWORD)@$(POSTGRES_URL):5432/$(POSTGRES_DB)"
          envFrom:
            - configMapRef:
                name: projects-config
            - secretRef:
                name: projects-secret